export const items = [
  {
    id: 1,
    color: 'from-[#d7d2cc] to-[#304352]',
    title: 'Next Portfolio',
    desc: 'An interactive portfolio built with Next.js and Tailwind CSS, showcasing my web development skills. Using Framer Motion.',
    video: '/1.mov',
    link: '',
    codeLink: 'https://github.com/LBondarchuk/portfolio',
  },
  {
    id: 2,
    color: 'from-[#304352] to-[#ffcc33]',
    title: 'React Mobile',
    desc: 'This app is Apple electronics store that has multiple product categories, a product cart, and a list of favorites',
    video: './2.mov',
    link: 'https://lbondarchuk.github.io/react_phone-catalog/#/',
    codeLink: 'https://github.com/LBondarchuk/react_phone-catalog/tree/develop',
  },
  {
    id: 3,
    color: 'from-[#ffcc33] to-[#525252]',
    title: 'Mind Merge (Pure JS)',
    desc: 'This game is based on the logic of the mega-popular game 2048. It is a game for developing logical thinking and memory.',
    video: './3.mov',
    link: 'https://lbondarchuk.github.io/js_2048_game/',
    codeLink: 'https://github.com/LBondarchuk/js_2048_game/tree/develop',
  },
  {
    id: 4,
    color: 'from-[#525252] to-[#ffcc33]',
    title: 'React Task Organizer App',
    desc: 'The Task Organizer App is an interactive tool designed for organizing and tracking tasks using a tree-like structure. ',
    video: './4.mov',
    link: 'https://lbondarchuk.github.io/task-app/',
    codeLink: 'https://github.com/LBondarchuk/task-app',
  },
];
